# Generated by Django 4.0 on 2022-01-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('open', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=50)),
                ('low', models.CharField(max_length=50)),
                ('change', models.CharField(max_length=50)),
                ('change_percent', models.CharField(max_length=50)),
                ('volume_lacs', models.CharField(max_length=50)),
                ('turnover_crs', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'NiftyModel',
            },
        ),
    ]
