# Generated by Django 4.0 on 2022-01-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niftymodel',
            old_name='symbol',
            new_name='label',
        ),
    ]
